CREATE TABLE companies
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE contracts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    number      VARCHAR(255)                            NOT NULL,
    start_date  date                                    NOT NULL,
    expiry_date date,
    employee_id BIGINT                                  NOT NULL,
    position_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_contracts PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    company_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employee_statuses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255)                            NOT NULL,
    start_date  date                                    NOT NULL,
    expiry_date date,
    number      INTEGER,
    employee_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee_statuses PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted    BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    first_name    VARCHAR(100)                            NOT NULL,
    last_name     VARCHAR(100)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    date_of_birth date                                    NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    address    VARCHAR(400)                            NOT NULL,
    company_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE positions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted    BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255)                            NOT NULL,
    department_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_positions PRIMARY KEY (id)
);

CREATE TABLE schedule_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    schedule_id BIGINT                                  NOT NULL,
    day_of_week VARCHAR(255)                            NOT NULL,
    shift       INTEGER                                 NOT NULL,
    start_time  time WITHOUT TIME ZONE                  NOT NULL,
    end_time    time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_schedule_items PRIMARY KEY (id)
);

CREATE TABLE schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    location_id BIGINT                                  NOT NULL,
    start_date  date                                    NOT NULL,
    expiry_date date,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

CREATE TABLE timesheets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    date        date                                    NOT NULL,
    entry_time  time WITHOUT TIME ZONE                  NOT NULL,
    exit_time   time WITHOUT TIME ZONE                  NOT NULL,
    location_id BIGINT                                  NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_timesheets PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_POSITION FOREIGN KEY (position_id) REFERENCES positions (id);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE employee_statuses
    ADD CONSTRAINT FK_EMPLOYEE_STATUSES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE locations
    ADD CONSTRAINT FK_LOCATIONS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE schedule_items
    ADD CONSTRAINT FK_SCHEDULE_ITEMS_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedules (id);

ALTER TABLE timesheets
    ADD CONSTRAINT FK_TIMESHEETS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE timesheets
    ADD CONSTRAINT FK_TIMESHEETS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);