CREATE TABLE groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE groups_employees
(
    employee_id BIGINT NOT NULL,
    group_id    BIGINT NOT NULL,
    CONSTRAINT pk_groups_employees PRIMARY KEY (employee_id, group_id)
);

ALTER TABLE groups_employees
    ADD CONSTRAINT fk_groemp_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

CREATE TABLE setting_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted    BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    setting_id    BIGINT                                  NOT NULL,
    day_type      VARCHAR(255),
    day_of_week   VARCHAR(255),
    value         DOUBLE PRECISION,
    integer_value INTEGER,
    string_value  VARCHAR(100),
    CONSTRAINT pk_setting_items PRIMARY KEY (id)
);

CREATE TABLE settings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    target      VARCHAR(255)                            NOT NULL,
    parameter   VARCHAR(255)                            NOT NULL,
    start_date  date                                    NOT NULL,
    expiry_date date,
    CONSTRAINT pk_settings PRIMARY KEY (id)
);

CREATE TABLE settings_employees
(
    employee_id BIGINT NOT NULL,
    setting_id  BIGINT NOT NULL,
    CONSTRAINT pk_settings_employees PRIMARY KEY (employee_id, setting_id)
);

CREATE TABLE settings_groups
(
    group_id   BIGINT NOT NULL,
    setting_id BIGINT NOT NULL,
    CONSTRAINT pk_settings_groups PRIMARY KEY (group_id, setting_id)
);

ALTER TABLE setting_items
    ADD CONSTRAINT FK_SETTING_ITEMS_ON_SETTING FOREIGN KEY (setting_id) REFERENCES settings (id);

ALTER TABLE groups_employees
    ADD CONSTRAINT fk_groemp_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE settings_employees
    ADD CONSTRAINT fk_setemp_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE settings_employees
    ADD CONSTRAINT fk_setemp_on_setting FOREIGN KEY (setting_id) REFERENCES settings (id);

ALTER TABLE settings_groups
    ADD CONSTRAINT fk_setgro_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE settings_groups
    ADD CONSTRAINT fk_setgro_on_setting FOREIGN KEY (setting_id) REFERENCES settings (id);