CREATE TABLE calendar
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    year        INTEGER                                 NOT NULL,
    date        date                                    NOT NULL,
    holiday     SMALLINT                                NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_calendar PRIMARY KEY (id)
);

ALTER TABLE setting_items
    ADD inversion BOOLEAN;