CREATE TABLE calculations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    pay_period  VARCHAR(7)                              NOT NULL,
    payroll_id  BIGINT                                  NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    amount      DOUBLE PRECISION                        NOT NULL,
    tariff      DOUBLE PRECISION                        NOT NULL,
    sum         DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_calculations PRIMARY KEY (id)
);

CREATE TABLE deduction_templates
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_deduction_templates PRIMARY KEY (id)
);

CREATE TABLE deductions
(
    id          BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    CONSTRAINT pk_deductions PRIMARY KEY (id)
);

CREATE TABLE earning_templates
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_earning_templates PRIMARY KEY (id)
);

CREATE TABLE earnings
(
    id          BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    CONSTRAINT pk_earnings PRIMARY KEY (id)
);

CREATE TABLE groups_deductions
(
    deduction_id BIGINT NOT NULL,
    group_id     BIGINT NOT NULL,
    CONSTRAINT pk_groups_deductions PRIMARY KEY (deduction_id, group_id)
);

CREATE TABLE groups_earningrs
(
    earning_id BIGINT NOT NULL,
    group_id   BIGINT NOT NULL,
    CONSTRAINT pk_groups_earningrs PRIMARY KEY (earning_id, group_id)
);

CREATE TABLE payrolls
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                VARCHAR(31),
    is_deleted          BOOLEAN,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    name                VARCHAR(100)                            NOT NULL,
    description         VARCHAR(255),
    basis               VARCHAR(255),
    rate                DOUBLE PRECISION                        NOT NULL,
    frequency           VARCHAR(255)                            NOT NULL,
    reverse_calculation BOOLEAN,
    start_date          date                                    NOT NULL,
    expiry_date         date,
    CONSTRAINT pk_payrolls PRIMARY KEY (id)
);

ALTER TABLE timesheets
    ADD timecode VARCHAR(255);

ALTER TABLE timesheets
    ALTER COLUMN timecode SET NOT NULL;

ALTER TABLE calculations
    ADD CONSTRAINT FK_CALCULATIONS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE calculations
    ADD CONSTRAINT FK_CALCULATIONS_ON_PAYROLL FOREIGN KEY (payroll_id) REFERENCES payrolls (id);

ALTER TABLE deductions
    ADD CONSTRAINT FK_DEDUCTIONS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE deductions
    ADD CONSTRAINT FK_DEDUCTIONS_ON_ID FOREIGN KEY (id) REFERENCES deduction_templates (id);

ALTER TABLE deduction_templates
    ADD CONSTRAINT FK_DEDUCTION_TEMPLATES_ON_ID FOREIGN KEY (id) REFERENCES payrolls (id);

ALTER TABLE earnings
    ADD CONSTRAINT FK_EARNINGS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE earnings
    ADD CONSTRAINT FK_EARNINGS_ON_ID FOREIGN KEY (id) REFERENCES earning_templates (id);

ALTER TABLE earning_templates
    ADD CONSTRAINT FK_EARNING_TEMPLATES_ON_ID FOREIGN KEY (id) REFERENCES payrolls (id);

ALTER TABLE groups_deductions
    ADD CONSTRAINT fk_groded_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE groups_deductions
    ADD CONSTRAINT fk_groded_on_payroll FOREIGN KEY (deduction_id) REFERENCES payrolls (id);

ALTER TABLE groups_earningrs
    ADD CONSTRAINT fk_groear_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE groups_earningrs
    ADD CONSTRAINT fk_groear_on_payroll FOREIGN KEY (earning_id) REFERENCES payrolls (id);

ALTER TABLE timesheets
    ALTER COLUMN entry_time DROP NOT NULL;

ALTER TABLE timesheets
    ALTER COLUMN exit_time DROP NOT NULL;