CREATE TABLE calculation_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted     BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    calculation_id BIGINT                                  NOT NULL,
    stage          VARCHAR(100)                            NOT NULL,
    message        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_calculation_log PRIMARY KEY (id)
);

ALTER TABLE calculation_log
    ADD CONSTRAINT FK_CALCULATION_LOG_ON_CALCULATION FOREIGN KEY (calculation_id) REFERENCES calculations (id);