CREATE TABLE algorithm_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted   BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    algorithm_id BIGINT                                  NOT NULL,
    "order"      INTEGER                                 NOT NULL,
    description  VARCHAR(255),
    CONSTRAINT pk_algorithm_items PRIMARY KEY (id)
);

CREATE TABLE algorithms
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    payroll_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_algorithms PRIMARY KEY (id)
);

ALTER TABLE algorithms
    ADD CONSTRAINT uc_algorithms_payroll UNIQUE (payroll_id);

ALTER TABLE algorithms
    ADD CONSTRAINT FK_ALGORITHMS_ON_PAYROLL FOREIGN KEY (payroll_id) REFERENCES payrolls (id);

ALTER TABLE algorithm_items
    ADD CONSTRAINT FK_ALGORITHM_ITEMS_ON_ALGORITHM FOREIGN KEY (algorithm_id) REFERENCES algorithms (id);